// <auto-generated />
using Bakery.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bakery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191227103143_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bakery.Models.Bread", b =>
                {
                    b.Property<int>("BreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBreadOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BreadId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Breads");

                    b.HasData(
                        new
                        {
                            BreadId = 1,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2017/04/01/12/36/bread-2193537_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/04/01/12/36/bread-2193537_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = true,
                            LongDescription = "Älskade limpmacka! Nu Sverige mest sålda limpa. PågenLimpan var en av de första skivade limporna när den lanserades i början av 90-talet. Den klassiska svenska limpan är bakad på vete och siktat rågmjöl som tillsammans med surdeg och sirap ger en härlig mjuk och saftigt limpa. Njut av en Svensk klassiker!",
                            Name = "Limpan",
                            Price = 20m,
                            ShortDescription = "Älskade limpmacka!"
                        },
                        new
                        {
                            BreadId = 2,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2018/10/09/20/27/bread-3735903_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/10/09/20/27/bread-3735903_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = false,
                            LongDescription = "Fantastiskt gott osötat surdegsbröd bakat på de allra finaste råvarorna. Bakat med solmoget vete och få ingredienser – inga konstigheter. Njut av en skiva Levain eller två, när du blir sugen på något gott och härligt!",
                            Name = "Levain",
                            Price = 20m,
                            ShortDescription = "Fantastiskt gott osötat surdegsbröd"
                        },
                        new
                        {
                            BreadId = 3,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2015/12/05/11/04/toast-1077984_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2015/12/05/11/04/toast-1077984_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = false,
                            LongDescription = "Härligt rostbröd med tydlig och balanserad smak - Jättegott! Lanserades 1960 och är Sveriges första skivade formfranska. Idén kom från USA där just skivad formfranska var oerhört populärt. I Sverige tog vi snabbt till oss den amerikanska trenden med att rosta brödet och JätteFranska blev folkets favorit.",
                            Name = "Jättefranska",
                            Price = 20m,
                            ShortDescription = "Härligt rostbröd."
                        },
                        new
                        {
                            BreadId = 4,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2016/10/22/17/10/bread-1761197_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/10/22/17/10/bread-1761197_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = false,
                            LongDescription = "Bästa starten på dagen! Mer lingon och mindre socker gör LingonGrova Special till ett lite nyttigare alternativ. Sveriges mest älskade bröd ger en riktigt god start på vilken morgon som helst.",
                            Name = "LingonGrova Special",
                            Price = 20m,
                            ShortDescription = "Bästa starten på dagen!"
                        },
                        new
                        {
                            BreadId = 5,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2019/11/21/14/46/white-bread-4642686_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/11/21/14/46/white-bread-4642686_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = false,
                            LongDescription = "Bästa starten på dagen! Sveriges mest älskade bröd är en oumbärlig del av frukosten. Fullkorn, surdeg och svenska lingon gör LingonGrova till en riktigt god start på vilken morgon som helst.",
                            Name = "LingonGrova",
                            Price = 20m,
                            ShortDescription = "Bästa starten på dagen!"
                        },
                        new
                        {
                            BreadId = 6,
                            AllergyInformation = "",
                            CategoryId = 2,
                            ImageThumbnailUrl = "https://cdn.pixabay.com/photo/2018/06/19/09/34/bread-3484107_960_720.jpg",
                            ImageUrl = "https://cdn.pixabay.com/photo/2018/06/19/09/34/bread-3484107_960_720.jpg",
                            InStock = true,
                            IsBreadOfTheWeek = false,
                            LongDescription = "Smakrikt rustikt surdegsbröd med malt och groddade rågkärnor. Bakat med mjöl från vår egen kvarn och få ingredienser – inga konstigheter. Njut av den gyllengräddade skorpan och den milt syrliga smaken!",
                            Name = "Råg Levain",
                            Price = 20m,
                            ShortDescription = "Smakrikt rustikt surdegsbröd"
                        });
                });

            modelBuilder.Entity("Bakery.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "White breads"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Dark breads"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Coffee breads"
                        });
                });

            modelBuilder.Entity("Bakery.Models.Bread", b =>
                {
                    b.HasOne("Bakery.Models.Category", "Category")
                        .WithMany("Breads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
